name: Continous Delivery (CD)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: pierod04/agrotech-backend
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'

      - name: Verificar entorno
        run: |
          java -version
          mvn -v
          docker --version

      - name: Compilar proyecto con tests
        run: mvn clean package -DskipTests=false

      - name: Construir imagen Docker
        run: docker build -t $DOCKER_IMAGE .

      - name: Login y push a Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $DOCKER_IMAGE
          

      - name: Llamar a Continous Deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}