name: Continuous Delivery (CD)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: pierod04/agrotech-backend
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache de dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Descargar dependencias
        run: mvn dependency:go-offline

      - name: Verificar conexión a la base de datos remota
        run: |
          echo "Host: $MYSQL_HOST"
          echo "Puerto: $MYSQL_PORT"
          echo "Usuario: $MYSQL_USER"
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql --host="$MYSQL_HOST" --port="$MYSQL_PORT" --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; SHOW TABLES;"

      - name: Compilar proyecto con tests
        run: mvn -B clean package -DskipTests=false

      - name: Construir imagen Docker
        run: docker build -t $DOCKER_IMAGE .

      - name: Login y push a Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push $DOCKER_IMAGE

      - name: Llamar a Continous Deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}