name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Hacer deploy de la imagen en Render
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST $DEPLOY_HOOK_URL